eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
  instance:
    prefer-ip-address: true
    
spring:  
  application:
    name: USERSERVICEdev
